// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $LoginComp from "./islands/LoginComp.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $Register from "./islands/Register.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/LoginComp.tsx": $LoginComp,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/Register.tsx": $Register,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
